name: Profile QA - full repository
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  nictiz-r4-qa-full:
    name: Loose QA on the entire repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: qa acme
        uses: ArdonToonstra/qa-tooling-fhir-r4@0.3.0
        with:
          changed-only: false
          verbosity-level: warning
          best-practice-warnings: false
          suppress-display-issues: true
